### ISSUE TITLE
'till' argument in downward migrations should stop _before_ undoing that migration

### ISSUE THREAD

**Issue by kael-shipman** [mbucc/shmig#48]
@mbucc, again, very sorry to pepper you with all this stuff. I hope I'm not bothering you too much. (If I am, I can just maintain my own fork of shmig and not worry about trying to stay compatible, but of course, I'd rather there only be one shmig ;).)

This time I've got a somewhat more philosophical issue. When I run `shmig up till=some-migration`, I expect `some-migration` to have been applied. Similarly, when I run `shmig down till=some-migration`, _I still expect `some-migration` to be applied._

Think of it this way: Assuming `123456789-some_migration.sql` is the most recent migration, the following calls should produce _no state changes at all._

```sh
shmig up till=123456789
shmig down till=123456789
shmig up till=123456789
shmig down till=123456789
```

This makes sense because the `till` argument should presumably indicate that I want to be _on that migration._

Currently, however, the `till` argument produces the desired effect on upward migrations, but it runs the downward migration _through_ the `till` argument, not _to_ it.

**Comment by mbucc** [comment]
On Tue, Jul 17, 2018 at 10:34 PM, Kael Shipman <notifications@github.com>
wrote:

> I'd rather there only be one shmig ;)
>

+1.

This is all good stuff, I'll get to it, just not as fast as you do.  :)

**Comment by mbucc** [comment]
Actually, the current behavior is what I would have guessed.  Until to me means up to but not including.    The descending case is confusing, I agree, but it was my first guess based on things like (i = 0; i<10;i++) (open on lower end, closed on top) and SQL date range where clauses (again, open on lower end, and closed on the top).

I think the commands could be named better but I think the behavior is OK.

It's also a backward incompatible change, so I need a stronger rationale to justify potentially breaking other people's working scripts.  (Assuming someone other than you and I are using this in production ... :)

Since this
